package dev.jdtech.jellyfin.qrsetup

import dev.jdtech.jellyfin.backup.BackupCrypto
import java.util.Base64
import kotlinx.serialization.json.Json

/**
 * Pure encode/decode of a [QrConfigEnvelope] to/from the string that actually gets put in the QR
 * code - no `ServerDatabaseDao`/`AppPreferences` dependency (see [QrConfigManager] for the
 * DB/prefs-touching half), so this is plain-JVM unit-testable and not DI-wired.
 */
object QrConfigCodec {
    private val json = Json { prettyPrint = false }

    class UnsupportedVersionException(val payloadVersion: Int) :
        Exception(
            "This QR code was generated by a newer version of Findroid+ (payload version $payloadVersion)"
        )

    class InvalidPayloadException : Exception("Not a valid Findroid+ setup code")

    /** @throws BackupCrypto.PasswordRequiredException, BackupCrypto.WrongPasswordException */
    fun decodePayload(raw: String, password: String?): QrConfigEnvelope {
        val bytes =
            try {
                Base64.getDecoder().decode(raw)
            } catch (e: IllegalArgumentException) {
                throw InvalidPayloadException()
            }
        val plainBytes =
            try {
                BackupCrypto.decode(bytes, password)
            } catch (e: BackupCrypto.CorruptBackupException) {
                throw InvalidPayloadException()
            }
        val envelope =
            try {
                json.decodeFromString(QrConfigEnvelope.serializer(), String(plainBytes))
            } catch (e: Exception) {
                throw InvalidPayloadException()
            }
        if (envelope.version > QrConfigEnvelope.CURRENT_VERSION) {
            throw UnsupportedVersionException(envelope.version)
        }
        return envelope
    }

    fun encodePayload(envelope: QrConfigEnvelope, password: String?): String {
        val plainBytes = json.encodeToString(QrConfigEnvelope.serializer(), envelope).toByteArray()
        val bytes = BackupCrypto.encode(plainBytes, password)
        return Base64.getEncoder().encodeToString(bytes)
    }
}
